<?php

/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @see \Magestore\Bannerslider\Block\Adminhtml\Form\Renderer\Fieldset\Element
 */

/** @var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element $block */
/** @var \Magento\Framework\Escaper $escaper */

$element = $block->getElement();
$note = $element->getNote() ? '<div class="note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox' || $element->getExtType() == 'radio';
$addOn = $element->getBeforeElementHtml() || $element->getAfterElementHtml();
$fieldId = ($element->getHtmlId()) ? ' id="attribute-' . $element->getHtmlId() . '-container"' : '';
$fieldClass = "field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required' : '';
$fieldClass .= ($note) ? ' with-note' : '';

$fieldAttributes = \sprintf('%s class="%s" %s', $fieldId, $fieldClass, $block->getUiId('form-field', $element->getId()));
?>

<?php $block->checkFieldDisable() ?>
<?php
$elementToggleCode = $element->getToggleCode()
    ? $element->getToggleCode()
    : 'toggleValueElements(this, this.parentNode.parentNode.parentNode)';
?>
<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?= $element->getElementHtml() ?>
    <?php else: ?>
        <div<?= $fieldAttributes ?> data-attribute-code="<?= $escaper->escapeHtmlAttr($element->getHtmlId()) ?>" data-apply-to="<?= $escaper->escapeHtml($this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($element->hasEntityAttribute() ? $element->getEntityAttribute()->getApplyTo() : [])) ?>">
            <?php if ($elementBeforeLabel): ?>
                <?= $block->getElementHtml() ?>
                <?= $element->getLabelHtml() ?>
                <?= $escaper->escapeHtml($note) ?>
            <?php else: ?>
                <?= $element->getLabelHtml() ?>
                <div class="control">
                    <?= ($addOn) ? '<div class="addon">' . $block->getElementHtml() . '</div>' : $block->getElementHtml(); ?>
                    <?= $note ?>
                </div>
            <?php endif; ?>
            <div class="field-service" value-scope="<?= $block->getScopeLabel() ?>">
                <?php if ($block->canDisplayUseDefault()): ?>
                    <label for="<?= $element->getHtmlId() ?>_default" class="choice use-default">
                        <input <?php if ($element->getReadonly()): ?> disabled="disabled" <?php endif; ?> type="checkbox" name="use_default[<?= $block->getElementName() ?>]" class="use-default-control" id="<?= $escaper->escapeHtmlAttr($element->getHtmlId()) ?>_default" <?php if ($block->usedDefault()): ?> checked="checked" value="true" <?php else: ?> value="false" <?php endif; ?> />
                        <span class="use-default-label"><?= __('Use Default Value') ?></span>
                    </label>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery'], function($) {
        $('#<?= $element->getHtmlId() ?>_default').click(function(event) {
            $('#<?= $element->getHtmlId() ?>').prop('disabled', $(this).prop('checked'));
            $(this).val($(this).prop('checked'));
            if (this.id == 'page_image_default') {
                $('#page_image_delete').prop('disabled', $(this).prop('checked'));
                $('#page_image_delete').next().toggleClass('disabled');
            }
        });
    });
</script>
